"""Añadir campo email a User

Revision ID: 078d0055afb2
Revises: dc9c8f176179
Create Date: 2025-07-03 09:30:29.576005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078d0055afb2'
down_revision = 'dc9c8f176179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Añadir columna email
        batch_op.add_column(
            sa.Column('email', sa.String(length=120), nullable=True)
        )
        # Única constraint nombrada
        batch_op.create_unique_constraint(
            'uq_user_email',
            ['email']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Eliminar la constraint por nombre
        batch_op.drop_constraint(
            'uq_user_email',
            type_='unique'
        )
        # Eliminar la columna email
        batch_op.drop_column('email')
    # ### end Alembic commands ###
